FROM php:fpm


RUN apt-get update \
    && apt-get install -y \
    git \
    zip \
    unzip \
    vim \
    default-mysql-client

# install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN docker-php-ext-install pdo_mysql

# node.js install
RUN apt-get install -y nodejs npm && npm install n -g && n 16.13.2


WORKDIR /var/www/html