export const QUERY_KEY = {
  AUTH: 'auth',
  GUEST: 'guest',
  ADMIN: 'admin',
  BOXER: 'boxer',
  MATCH_SINGLE: 'match',
  MATCH_RESULT: 'match/result',
  FETCH_MATCHES: 'matches',
  FETCH_PAST_MATCHES: 'matches/past',
  FETCH_ALL_MATCHES: 'matches/all',
  DELETE_MATCH: 'match/delete',
  COMMENT: 'comment',
  COMMENT_NEW: 'comment/new',
  COMMENT_STATE: 'comment/state',
  PREDICTION: 'prediction',
  MATCH_PREDICTIONS: 'match/predictions',
} as const