export const CUSTOM_ERROR_CODE = {
  TITLE_ALREADY_HAS_OTHER_BOXER: 30,
  BOXER_ALREADY_HAS_MATCH: 31,
  BOXER_ALREADY_EXISTS: 32,
  UNABLE_TO_GENERATE_GUEST_TODAY: 40,
  BOXER_NOT_FOUND: 44,
  BOXER_DELETE_FAILED: 50,
  EXPIRED_TOKEN: 1050,
  INVALID_TOKEN: 1051,
} as const;
